version: "3.8"

services:
  greenlight:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-container
    environment:
      - GREENLIGHT_DB_DSN=postgres://greenlight:password@db:5432/greenlight?sslmode=disable
      - PORT=4000
    networks:
      - dev
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: greenlight
    networks:
      - dev
    volumes:
      - ./postgres:/var/lib/postgresql/data



networks:
  dev:
    driver: bridge

volumes:
  postgres: